package com.codingshuttle.TestingApp.controllers;

//import com.codingshuttle.TestingApp.TestContainerConfiguration;
import com.codingshuttle.TestingApp.dto.EmployeeDto;
import com.codingshuttle.TestingApp.entities.Employee;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.reactive.AutoConfigureWebTestClient;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Import;
import org.springframework.test.web.reactive.server.WebTestClient;

@AutoConfigureWebTestClient(timeout = "100000")
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
//@Import(TestContainerConfiguration.class)
public abstract class AbstractIntegrationTest {

    @Autowired
    protected WebTestClient webTestClient;


//     * Creates a fresh Employee entity for every test.
//     * ID is intentionally omitted because it is generated by the database.

    protected Employee createTestEmployee() {
        return Employee.builder()
                .name("Sujit")
                .email("jeetumbalkar@gmail.com")
                .salary(10000L)
                .build();
    }


//     * Creates a fresh EmployeeDto for API requests.
//     * ID is intentionally omitted because clients should not send IDs while creating resources.(post)

    protected EmployeeDto createTestEmployeeDto() {
        return EmployeeDto.builder()
                .name("Sujit")
                .email("jeetumbalkar@gmail.com")
                .salary(10000L)
                .build();
    }
}